### ISSUE TITLE
Previews in countess

### ISSUE THREAD

**Issue by genomematt** [genomematt/pebbles#2]
Currently there is no mechanism to process a limited number of reads for generating a preview.
This means the countess interface generates a preview from a full run, making it inefficient and unresponsive.

**Comment by nickzoic** [comment]
Hmm, yeah, CountESS's UI behaviour kind of depends on that being possible :-)

It looks like `pysam.AlignmentFile` is a generator, so `count_dict` could take a read limit and give up once `len(counts) >= row_limit` and/or after some number of records read from `call_mutations_from_pysam`.  It doesn't have to be strictly `row_limit` number of rows output, it's more like a guideline to get the right "shape" of data.

The file should only get read when you change that plugin's parameters though anyway ... although I only fixed that logic fairly recently I think.  I'll also (soon) be moving the preview calculation off to its own thread, which might also help resolve this as the UI responsiveness will be less affected.

I went looking for some public SAM/BAM files which I could use as a test but I'm having trouble finding any which successfully load in to pebbles but are big enough to be slow.

**Comment by genomematt** [comment]
I wanted to sit on what the shape consequences would be for different analyses, sorted vs unsorted input etc before I made an implementation decision. As you say the fixed number of rows from the source file is likely to be reasonable, and would only be an issue if they are all wildtype resulting in a null return.
Still probably the best option.
Will work up an option and find or generate some test data.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nickzoic** [comment]
Yeah, it's not 100% clear in a few situations.  It's also tricky when you read two large tables and then you want to join them: if you've only read the first 10,000 rows of each then odds are you might get 0 rows to join on, unless you sort the input files first.  It'd be nice to make it a little more dynamic somehow so that the join could ask its sources to keep going just a bit longer ...

**Comment by genomematt** [comment]
re-commited the fix to this on a branch that was not messed up relative to main.

**Comment by genomematt** [comment]
fixed in dev0.3
