### ISSUE TITLE
Handle absence of MD tags better

### ISSUE THREAD

**Issue by genomematt** [genomematt/pebbles#4]
If reads don't have MD tags an error is logged to the console.
This probably should raise a more visible error in the GUI as it will result in no variants being found

**Comment by nickzoic** [comment]
Yep, so plugins now get passed a "logger" object, which can be used to report non-fatal errors, warnings, info messages and also progress.  In the GUI, these will get displayed under the 'preview' pane.  In the command-line application these get logged to stdout and stderr.

**Comment by nickzoic** [comment]
In #6 I kinda had to reproduce the logic from `call_mutations_from_pysam` so I could catch and log this, but it's not really a good way to do it.

**Comment by genomematt** [comment]
Now fixed in dev0.3 branch passing countess logger into relevant pebbles functions
