### ISSUE TITLE
Document countess plugin install and usage

### ISSUE THREAD

**Issue by genomematt** [genomematt/pebbles#5]

**Comment by nickzoic** [comment]
In #6 I added an optional-dependencies into pyproject.toml so if you `pip install pebbles[countess]` it'll pull in the appropriate countess version, that might be a start :-)

**Comment by genomematt** [comment]
Should also add additional documentation around contributing, code of conduct, citing, add zenodo badge

**Comment by genomematt** [comment]
added in v0.3.0
